### ISSUE TITLE
Invalid code generator "async-import"

### ISSUE THREAD

**Issue by splincode** [shlomiassaf/ng-router-loader#14]
app.routes.ts

```
export const ROUTES: Routes = [
    {path: '', loadChildren: './modules/+home/home.module#HomeModule'}
];

```

```

ERROR in ./webapp/source/app/app.routes.ts
Module build failed: Error: ng-router-loader - Invalid code generator "async-import"
    at Loader.replaceSource (/home/splincode/Develop/blackbox/ui-util/node_modules/src/Loader.ts:104:29)
    at Loader.replace (/home/splincode/Develop/blackbox/ui-util/node_modules/src/Loader.ts:66:22)
    at Object.loader (/home/splincode/Develop/blackbox/ui-util/node_modules/index.ts:12:5)
 @ ./webapp/source/app/app.module.ts 14:0-38
 @ ./webapp/source/main.ts


```

**Comment by shlomiassaf** [comment]
No enough information.

Works in test.

Make sure your have the right version.
